/* Authentication */
export const AUTHENTICATED = 'AUTHENTICATED_USER'
export const UNAUTHENTICATED = 'UNAUTHENTICATED_USER'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'

/* General Actions */
export const GET_AVAILABLE_QUESTIONS = 'GET_AVAILABLE_QUESTIONS'
export const GET_ANSWERS = 'GET_ANSWERS'
export const ANSWER_QUESTION = 'ANSWER_QUESTION'
