/* Authentication */
export const AUTHENTICATED = 'AUTHENTICATED_USER'
export const UNAUTHENTICATED = 'UNAUTHENTICATED_USER'

/* Answer */
export const GET_ANSWERS = 'GET_ANSWERS'
export const ANSWER_QUESTION = 'ANSWER_QUESTION'

/* Question */
export const ADD_QUESTION = 'ADD_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const GET_AVAILABLE_QUESTION = 'GET_AVAILABLE_QUESTION'
export const GET_QUESTIONS = 'GET_QUESTIONS'

/* Report */
export const GET_DEMOGRAPHIC_GENDER = 'GET_DEMOGRAPHIC_GENDER'
export const GET_DEMOGRAPHIC_POSTCODE = 'GET_DEMOGRAPHIC_POSTCODE'
export const GET_DEMOGRAPHIC_AGE = 'GET_DEMOGRAPHIC_AGE'
export const GET_STATISTIC_AVG_WEEKLY_RESPONSES = 'GET_STATISTIC_AVG_WEEKLY_RESPONSES'
export const GET_STATISTIC_USER_LIST_BELLOW_SDVA = 'GET_STATISTIC_USER_LIST_BELLOW_SDVA'
